name: Save Nx cache
description: Saves the Nx computation cache for reuse by later runs

runs:
  using: composite
  steps:
    - uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: .nx/cache
        key: nx-${{ runner.os }}-${{ github.run_id }}
