/**
 * Shared visual language for the standalone auth screens (Login,
 * ForgotPassword, ResetPassword, SetPassword) — extracted from Login.tsx so
 * the whole account-lifecycle flow looks like one continuous experience
 * instead of four independently-styled pages.
 */
export const ease = { ease: 'linear', duration: 0.3 };

export const fadeIn = {
  initial: { opacity: 0 },
  animate: { opacity: 1 },
  transition: ease,
};

export const stepVariants = {
  initial: { opacity: 0, y: 6 },
  animate: { opacity: 1, y: 0, transition: ease },
  exit: { opacity: 0, y: -6, transition: { ...ease, duration: 0.18 } },
};

export const s: Record<string, React.CSSProperties> = {
  page: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    overflow: 'hidden',
    background: '#f9f9f9',
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
  },
  bg: {
    position: 'absolute',
    inset: 0,
    pointerEvents: 'none',
    userSelect: 'none',
  },
  bgGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 1fr)',
    alignContent: 'start',
    padding: '60px 32px 0',
    gap: 2,
    color: '#ccc',
    fontSize: 12,
  },
  bgTh: { padding: '6px 10px', color: '#d8d8d8', fontSize: 11, fontWeight: 500, borderBottom: '1px solid #efefef' },
  bgTd: { padding: '8px 10px', color: '#e0e0e0', fontSize: 12, borderBottom: '1px solid #f5f5f5' },
  overlay: {
    position: 'absolute',
    inset: 0,
    backdropFilter: 'blur(4px)',
    background: 'rgba(249,249,249,0.6)',
  },
  modal: {
    position: 'relative',
    zIndex: 10,
    background: '#ffffff',
    borderRadius: 16,
    padding: '36px 32px 32px',
    width: 340,
    boxShadow: '0 2px 12px rgba(0,0,0,0.08), 0 20px 60px rgba(0,0,0,0.08)',
    border: '1px solid #ebebeb',
  },
  logoWrap: {
    display: 'flex',
    justifyContent: 'center',
    marginBottom: 24,
  },
  logo: {
    width: 48,
    height: 48,
    background: '#111827',
    borderRadius: 12,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 15,
    fontWeight: 600,
    color: '#1a1a1a',
    textAlign: 'center',
    margin: '0 0 20px',
  },
  subtitle: {
    fontSize: 12,
    color: '#888',
    textAlign: 'center',
    margin: '-12px 0 20px',
    lineHeight: 1.5,
  },
  label: {
    display: 'block',
    fontSize: 12,
    fontWeight: 500,
    color: '#666',
    marginBottom: 4,
  },
  input: {
    width: '100%',
    padding: '9px 12px',
    border: '1px solid #e5e5e5',
    borderRadius: 8,
    fontSize: 13,
    color: '#1a1a1a',
    outline: 'none',
    fontFamily: 'inherit',
    boxSizing: 'border-box',
    marginBottom: 10,
    background: '#fafafa',
    transition: 'border-color 0.15s',
  },
  submitBtn: {
    width: '100%',
    padding: '9px 16px',
    background: '#1a1a1a',
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'inherit',
    transition: 'opacity 0.15s',
    boxSizing: 'border-box',
  },
  emailChip: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '7px 12px',
    background: '#f5f5f5',
    border: '1px solid #ebebeb',
    borderRadius: 20,
    fontSize: 13,
    color: '#555',
    marginBottom: 14,
    width: 'fit-content',
    maxWidth: '100%',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  emailDot: {
    width: 7,
    height: 7,
    borderRadius: '50%',
    background: '#aaa',
    flexShrink: 0,
  },
  eyeBtn: {
    position: 'absolute',
    right: 10,
    top: '50%',
    transform: 'translateY(-65%)',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 4,
    display: 'flex',
    alignItems: 'center',
  },
  error: {
    color: '#dc2626',
    fontSize: 12,
    marginBottom: 8,
    padding: '6px 10px',
    background: '#fef2f2',
    borderRadius: 6,
    border: '1px solid #fecaca',
  },
  success: {
    color: '#166534',
    fontSize: 12,
    marginBottom: 8,
    padding: '6px 10px',
    background: '#f0fdf4',
    borderRadius: 6,
    border: '1px solid #bbf7d0',
  },
  backBtn: {
    display: 'block',
    width: '100%',
    marginTop: 12,
    background: 'none',
    border: 'none',
    color: '#aaa',
    fontSize: 12,
    cursor: 'pointer',
    fontFamily: 'inherit',
    textAlign: 'center',
    transition: 'color 0.15s',
  },
  strengthList: {
    margin: '-6px 0 10px',
    padding: '0 0 0 16px',
    fontSize: 11,
    color: '#dc2626',
  },
};
