// class-validator/class-transformer decorators need reflect-metadata loaded
// before any decorated class is touched. NestJS's own bootstrap (main.ts)
// loads it implicitly via @nestjs/core, but a unit test that imports a
// decorated class directly — without ever going through Nest bootstrap —
// does not get that for free.
import 'reflect-metadata';

// RabThrottlerModule skips rate limiting whenever this is 'true' AND
// JEST_WORKER_ID is set (the latter can never be true outside an actual
// Jest run, so this can't leak into a real deployment even by accident).
// The integration suite shares one IP across many spec files that each hit
// /auth/login repeatedly within the same 60s window — none of that is real
// abuse. `rate-limiting.integration.spec.ts` flips this back to 'false' at
// its own top level to exercise the real throttle end-to-end.
process.env.RAB_DISABLE_RATE_LIMIT = 'true';

// EMAIL_DRIVER is forced to LOGGER for every Jest run, unconditionally,
// regardless of whatever `.env` on disk currently says. `EnvironmentModule`'s
// `ConfigModule.forRoot()` loads `.env` for a test run exactly like it does
// for a real boot (nothing about `AppModule` distinguishes "under Jest" on
// its own) — so if a developer's local `.env` is configured with a real
// SMTP/Resend provider for manual testing (this repo's own convention:
// `.env` is real, working, gitignored, per-developer), every integration
// test that creates a Staff/Manager account or triggers a password-reset/
// invitation email would silently fire real outbound email to whatever
// fake `@example.test` address that test generated. This happened for
// real, once — confirmed via real Gmail bounce-back notifications for
// `staff-*@example.test`/`mgr-*@example.test`/etc. addresses generated by
// this session's own integration test runs, traced to exactly this gap.
// Set here (a `setupFiles` entry, so it runs before any module — including
// `dotenv`'s own load inside `ConfigModule.forRoot()` — sees `process.env`)
// so no test can ever reach a real email provider, structurally, no matter
// what any developer's local `.env` is configured to do for manual testing.
process.env.EMAIL_DRIVER = 'LOGGER';
