name: ci-ui

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ci-ui-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  changed:
    uses: ./.github/workflows/changed-files.yaml

  test:
    needs: changed
    if: needs.changed.outputs.ui == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/yarn-install
      - uses: ./.github/actions/restore-cache
      - run: npx nx run-many -t lint -p rab-ui
      - run: npx nx run-many -t test -p rab-ui
      - run: npx nx run rab-ui:build
      - uses: ./.github/actions/save-cache
        if: always()
